// Re-export shim — moved to @agents/sdk/context/plugin/ops
export {
  type BuildResult,
  buildResultSuccess,
  countStatuses,
  deriveStatus,
  listPlugins,
  PLUGINS_DIR,
  Plugin,
  PROJECT_ROOT,
  printBuildSummary,
  printValidationResult,
  type SourceDef,
  type SourceStatus,
  type SourcesFile,
  type SourcesMap,
  STATUS_ICONS,
  sourceToDict,
  type ValidationResult,
  validateMarketplace,
  validatePlugin,
} from '@agents/sdk/context/plugin/ops'
