/**
 * catalog-availability.test.ts — Unit tests for catalog.ts Phase 2
 *
 * Run with: bun test cli/test/catalog-availability.test.ts
 */

import { describe, expect, it } from 'bun:test'
import { parseTodoYaml, uniqueRepos } from '../src/lib/catalog'

// ---------------------------------------------------------------------------
// parseTodoYaml
// ---------------------------------------------------------------------------

describe('parseTodoYaml', () => {
  it('parses a standard org/repo@skill entry', () => {
    const result = parseTodoYaml('anthropics/skills@pdf')
    expect(result).toEqual([{ source: 'anthropics/skills', skill: 'pdf' }])
  })

  it('parses a YAML list entry (- org/repo@skill)', () => {
    const result = parseTodoYaml('- anthropics/skills@pdf')
    expect(result).toEqual([{ source: 'anthropics/skills', skill: 'pdf' }])
  })

  it('skips blank lines', () => {
    const result = parseTodoYaml('\n\n')
    expect(result).toEqual([])
  })

  it('skips comment lines', () => {
    const result = parseTodoYaml('# this is a comment')
    expect(result).toEqual([])
  })

  it('skips HTTP URLs', () => {
    const result = parseTodoYaml('https://gpa-mcp.genai.prd.aws.saccap.int')
    expect(result).toEqual([])
  })

  it('skips HTTPS URLs', () => {
    const result = parseTodoYaml('https://github.com/anthropics/skills/tree/main/pdf')
    expect(result).toEqual([])
  })

  it('skips entries without @ separator', () => {
    const result = parseTodoYaml('anthropics/skills')
    expect(result).toEqual([])
  })

  it('skips entries with multiple slashes (tree/commit refs)', () => {
    // anthropics/skills/tree/main/pdf has >1 slash before @
    const result = parseTodoYaml('anthropics/skills/tree/main@pdf')
    expect(result).toEqual([])
  })

  it('parses multiple entries correctly', () => {
    const input = [
      '# Comment',
      'anthropics/skills@pdf',
      'anthropics/skills@xlsx',
      'wshobson/agents@foo',
      'https://example.com/skip-me',
      '',
      '- ComposioHQ/awesome-claude-skills@content-research-writer',
    ].join('\n')

    const result = parseTodoYaml(input)
    expect(result).toHaveLength(4)
    expect(result[0]).toEqual({ source: 'anthropics/skills', skill: 'pdf' })
    expect(result[1]).toEqual({ source: 'anthropics/skills', skill: 'xlsx' })
    expect(result[2]).toEqual({ source: 'wshobson/agents', skill: 'foo' })
    expect(result[3]).toEqual({
      source: 'ComposioHQ/awesome-claude-skills',
      skill: 'content-research-writer',
    })
  })

  it('handles skill names with hyphens and underscores', () => {
    const result = parseTodoYaml('owner/repo@skill-name_v2.0')
    expect(result).toEqual([{ source: 'owner/repo', skill: 'skill-name_v2.0' }])
  })

  it('handles repo names with dots and hyphens', () => {
    const result = parseTodoYaml('owner/my-repo.v2@skill')
    expect(result).toEqual([{ source: 'owner/my-repo.v2', skill: 'skill' }])
  })
})

// ---------------------------------------------------------------------------
// uniqueRepos
// ---------------------------------------------------------------------------

describe('uniqueRepos', () => {
  it('deduplicates repos from multiple entries', () => {
    const entries = [
      { source: 'anthropics/skills', skill: 'pdf' },
      { source: 'anthropics/skills', skill: 'xlsx' },
      { source: 'wshobson/agents', skill: 'foo' },
    ]
    const repos = uniqueRepos(entries)
    expect(repos).toHaveLength(2)
    expect(repos).toContain('anthropics/skills')
    expect(repos).toContain('wshobson/agents')
  })

  it('returns empty array for empty input', () => {
    expect(uniqueRepos([])).toEqual([])
  })

  it('preserves a single repo', () => {
    const entries = [{ source: 'owner/repo', skill: 'skill' }]
    expect(uniqueRepos(entries)).toEqual(['owner/repo'])
  })
})

// ---------------------------------------------------------------------------
// Integration: realistic .TODO.yaml sample
// ---------------------------------------------------------------------------

describe('realistic .TODO.yaml sample', () => {
  const SAMPLE_TODO = `
# External Skills Catalog - TODO list
# Format: org/repo@skill-name
# Generated by Phase 1 taxonomy engine

anthropics/skills@pdf
anthropics/skills@xlsx
anthropics/skills@pptx
anthropics/skills@brand-guidelines
wshobson/agents@research-agent
wshobson/agents@coding-agent
ComposioHQ/awesome-claude-skills@content-research-writer
ComposioHQ/awesome-claude-skills@lead-research-assistant
jezweb/claude-skills@tinacms
ovachiever/droid-tings@tinacms

# Non-standard entries to skip
https://gpa-mcp.genai.prd.aws.saccap.int
https://github.com/anthropics/skills/tree/main/pdf
- https://noriskillsets.dev/
lang-typescript-dev
cloud-cloudflare-workers-dev
`

  it('parses the sample correctly', () => {
    const entries = parseTodoYaml(SAMPLE_TODO)
    expect(entries).toHaveLength(10)

    // Verify deduplication
    const repos = uniqueRepos(entries)
    expect(repos).toHaveLength(5)
  })

  it('extracts correct unique repos', () => {
    const entries = parseTodoYaml(SAMPLE_TODO)
    const repos = uniqueRepos(entries)
    const repoSet = new Set(repos)

    expect(repoSet).toContain('anthropics/skills')
    expect(repoSet).toContain('wshobson/agents')
    expect(repoSet).toContain('ComposioHQ/awesome-claude-skills')
    expect(repoSet).toContain('jezweb/claude-skills') // cspell:disable-line
    expect(repoSet).toContain('ovachiever/droid-tings') // cspell:disable-line
  })

  it('does not include skipped entries', () => {
    const entries = parseTodoYaml(SAMPLE_TODO)
    const sources = entries.map((e) => e.source)

    // These should NOT appear
    expect(sources.some((s) => s.includes('https://'))).toBe(false)
    expect(sources).not.toContain('lang-typescript-dev')
    expect(sources).not.toContain('cloud-cloudflare-workers-dev')
  })
})
