test:
    echo "TODO: test all source files exist"
    echo "TODO: test LICENSE"
    echo "TODO: test CHANGELOG"
    echo "TODO: test README"
    echo "TODO: test .claude-plugin/plugin.json"

install: _agents _commands _configs _hooks _scripts _skills _styles

_agents:
    echo "TODO: copy all source agent files to target directory"

_commands:
    echo "TODO: copy all source command files to target directory"

_configs:
    echo "TODO: copy source mcp.json"
    echo "TODO: copy source lsp.json"

_hooks:
    echo "TODO: copy source hooks.json"
    echo "TODO: copy all source hook files to target directory"

_scripts:
    echo "TODO: copy all source script files to target directory"

_skills:
    echo "TODO: copy all source skill files to target directory"

_styles:
    echo "TODO: copy all source style files to target directory"
