---
# https://www.cloudnativedeepdive.com/implementing-a-registry-for-anthropic-skills-with-ag/
- https://www.spekter.io/
- https://mcpservers.org/
- https://chat.mcp.so
- https://glama.ai/mcp
- https://smithery.ai/
- https://oneskill.dev
- https://mcpmarket.com/tools/skills
- https://noriskillsets.dev/
- https://tilework.tech/
- https://skillregistry.io
- https://skills.re/
- https://agentman.ai/agentskills/
- https://solmaz.io/skillflag
- https://skillsfinder.ai/
- https://thingsolver.com/tools-registry/
- https://skillsmp.com/search
---
- https://github.com/alonw0/web-asset-generator
- https://github.com/anthropics/skills/tree/main/brand-guidelines
- https://github.com/anthropics/skills/tree/main/artifacts-builder
- https://github.com/anthropics/skills/tree/main/theme-factory
- https://github.com/ComposioHQ/awesome-claude-skills/tree/master/content-research-writer
- https://github.com/ComposioHQ/awesome-claude-skills/tree/master/lead-research-assistant
- https://github.com/michalparkola/tapestry-skills-for-claude-code
- https://github.com/K-Dense-AI/claude-scientific-skills
- https://github.com/chongdashu/cc-skills/tree/main/.claude/skills/site-metadata-generator
- https://github.com/yacosta738/yacosta738.github.io/tree/main/.ruler/skills/astro
- https://github.com/jezweb/claude-skills/tree/main/skills/tinacms
- https://github.com/ovachiever/droid-tings/tree/master/skills/tinacms
- https://github.com/Soborbo/claudeskills/tree/main/astro-ux

lang-typescript-dev
cloud-cloudflare-workers-dev
